name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name (used to fetch latest image)"
        required: false
      tag:
        description: "Exact image tag (optional, overrides branch)"
        required: false

env:
  IMAGE_NAME: eks-node-app-project

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Decide image tag
        id: resolve
        run: |
          IMAGE_BASE="${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME"

          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "Using provided tag"
            FINAL_TAG="${{ github.event.inputs.tag }}"
          
          elif [ -n "${{ github.event.inputs.branch }}" ]; then
            echo "Fetching latest tag for branch"

            BRANCH=$(echo "${{ github.event.inputs.branch }}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')

            # Fetch tags from Docker Hub
            TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME/tags?page_size=100" \
              | jq -r '.results[].name')

            # Filter tags by branch prefix and sort (latest first)
            FINAL_TAG=$(echo "$TAGS" | grep "^$BRANCH-" | sort -r | head -n 1)

            if [ -z "$FINAL_TAG" ]; then
              echo "No image found for branch: $BRANCH"
              exit 1
            fi

          else
            echo "Either tag or branch must be provided"
            exit 1
          fi

          IMAGE="$IMAGE_BASE:$FINAL_TAG"

          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "Resolved image: $IMAGE"

      - name: Print deployment info
        run: |
          echo "Deploying image: ${{ steps.resolve.outputs.image }}"