name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name (used to fetch latest image)"
        required: false
      tag:
        description: "Exact image tag (optional, overrides branch)"
        required: false

env:
  IMAGE_NAME: eks-node-app-project

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Decide image tag
        id: resolve
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "Using provided tag"
            FINAL_TAG="${{ github.event.inputs.tag }}"
          
          elif [ -n "${{ github.event.inputs.branch }}" ]; then
            echo "Fetching latest tag for branch"

            BRANCH=$(echo "${{ github.event.inputs.branch }}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')

            TAGS_JSON=$(curl -s "https://hub.docker.com/v2/repositories/${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_NAME/tags?page_size=100&ordering=last_updated")
            if ! echo "$TAGS_JSON" | jq -e '.results' > /dev/null 2>&1; then
              echo "ERROR: DockerHub API did not return expected results. Response:"
              echo "$TAGS_JSON"
              exit 1
            fi

            FINAL_TAG=$(echo "$TAGS_JSON" | jq -r '.results[].name' | grep "^$BRANCH-" | head -n 1)
            if [ -z "$FINAL_TAG" ]; then
              echo "ERROR: No tags found for branch '$BRANCH'"
              exit 1
            fi

          else
            echo "ERROR: Either tag or branch must be provided"
            exit 1
          fi

          echo "Resolved tag: $FINAL_TAG"
          echo "final_tag=$FINAL_TAG" >> $GITHUB_OUTPUT

      - name: Print resolved image
        run: |
          echo "Image Tag: ${{ steps.resolve.outputs.final_tag }}"